# Generated by Django 4.2.6 on 2023-10-23 18:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vendor', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='')),
                ('price', models.CharField(max_length=20)),
                ('accomodationLimit', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CurrentTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paid_amount', models.CharField()),
                ('paid_date', models.DateTimeField()),
                ('is_active', models.BooleanField()),
                ('tier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tier.tier')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_tier', to='vendor.vendoruser')),
            ],
        ),
    ]
