# Generated by Django 4.2.6 on 2023-10-31 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tier', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='method_of_payment',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_id',
            field=models.TextField(),
        ),
    ]
