# Generated by Django 4.2.6 on 2023-10-26 17:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tier', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='currenttier',
            name='paid_till',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
