# Generated by Django 5.0.1 on 2024-02-14 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tier', '0004_tiertransaction_paid_till'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tiertransaction',
            name='paid_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='tiertransaction',
            name='paid_till',
            field=models.DateField(),
        ),
    ]
