# Generated by Django 5.0.1 on 2024-02-14 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tier', '0005_alter_tiertransaction_paid_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tiertransaction',
            name='paid_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='tiertransaction',
            name='paid_till',
            field=models.DateTimeField(),
        ),
    ]
