# Generated by Django 5.0.1 on 2024-02-16 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
        ('notification', '0001_initial'),
        ('vendor', '0005_alter_vendorprofile_vendor'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Notificatio',
            new_name='Notification',
        ),
    ]
