# Generated by Django 5.0.1 on 2024-02-16 13:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0003_alter_notification_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='current_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 16, 19, 40, 52, 157063)),
        ),
    ]
