# Generated by Django 5.0.1 on 2024-02-17 13:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0004_notification_current_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='current_date',
        ),
        migrations.AddField(
            model_name='notification',
            name='added_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 17, 19, 29, 25, 870531)),
        ),
    ]
