# Generated by Django 5.0.1 on 2024-02-27 14:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0005_remove_notification_current_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='added_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 27, 20, 28, 41, 968937)),
        ),
    ]
