# Generated by Django 5.0.1 on 2024-02-28 07:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0008_notificationdevice_device_model_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='added_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 28, 13, 16, 25, 502194)),
        ),
        migrations.AlterField(
            model_name='notificationdevice',
            name='device_model',
            field=models.CharField(default='Unknown', max_length=50, null=True),
        ),
    ]
