# Generated by Django 5.0.1 on 2024-03-06 15:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0009_alter_notification_added_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='added_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 6, 21, 16, 56, 619370)),
        ),
    ]
