# Generated by Django 5.0.1 on 2024-03-22 08:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0016_alter_notification_added_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='added_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 22, 13, 57, 17, 416212)),
        ),
    ]
