# Generated by Django 5.0.1 on 2024-02-07 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingrequest',
            name='is_used',
            field=models.BooleanField(default=True),
        ),
    ]
