# Generated by Django 5.0.1 on 2024-03-06 15:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryitem',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='inventorylogs',
            name='date_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
