# Generated by Django 5.0.1 on 2024-03-07 07:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_inventoryitem_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorylogs',
            name='count',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='date_field',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
