# Generated by Django 5.0.1 on 2024-03-07 08:12

import inventory.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_inventorylogs_count_alter_inventoryitem_date_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryitem',
            name='date_field',
            field=models.DateField(default=inventory.models.current_date),
        ),
    ]
