# Generated by Django 5.0.1 on 2024-03-07 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_inventoryitem_date_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
