# Generated by Django 5.0.1 on 2024-02-10 06:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accomodation', '0009_room_room_count_alter_accommodation_monthly_rate'),
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(null=True, upload_to='reviews/')),
                ('is_deleted', models.BooleanField(default=False)),
                ('accommodation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accomodation.accommodation')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customer')),
            ],
        ),
    ]
