# Generated by Django 5.0.1 on 2024-02-10 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewmodel',
            name='added_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
