# Generated by Django 5.0.1 on 2024-02-11 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0002_reviewmodel_added_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewmodel',
            name='title',
            field=models.CharField(max_length=1),
        ),
    ]
