# Generated by Django 5.0.1 on 2024-02-12 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0003_alter_reviewmodel_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewmodel',
            name='title',
            field=models.DecimalField(decimal_places=1, max_digits=2),
        ),
    ]
