# Generated by Django 5.0.1 on 2024-02-12 20:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_alter_whishlist_user'),
        ('review', '0004_alter_reviewmodel_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewmodel',
            name='booking',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='booking.booking'),
        ),
    ]
