# Generated by Django 4.2.6 on 2023-11-03 06:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vendor', '0005_alter_vendorprofile_vendor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accommodation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('longitude', models.CharField(max_length=100)),
                ('latitude', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('hostel', 'Hostel'), ('hotel', 'Hotel'), ('rent_room', 'rent_room')], max_length=20)),
                ('monthly_rate', models.CharField(max_length=20, null=True)),
                ('number_of_washroom', models.IntegerField(null=True)),
                ('trash_dispose_availability', models.BooleanField(null=True)),
                ('parking_availability', models.BooleanField(null=True)),
                ('gym_availability', models.BooleanField(null=True)),
                ('swimming_pool_availability', models.BooleanField(null=True)),
                ('has_tier', models.BooleanField()),
                ('date_added', models.DateTimeField(auto_now=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(null=True)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendor.vendoruser')),
            ],
        ),
        migrations.CreateModel(
            name='HotelTiers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier_name', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('accomodation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accomodation.accommodation')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seater_beds', models.IntegerField(null=True)),
                ('ac_availability', models.BooleanField(null=True)),
                ('water_bottle_availability', models.BooleanField(null=True)),
                ('steam_iron_availability', models.BooleanField(null=True)),
                ('per_day_rent', models.DecimalField(decimal_places=2, max_digits=6)),
                ('fan_availability', models.BooleanField()),
                ('bed_availability', models.BooleanField(null=True)),
                ('sofa_availability', models.BooleanField(null=True)),
                ('mat_availability', models.BooleanField(null=True)),
                ('carpet_availability', models.BooleanField(null=True)),
                ('washroom_status', models.CharField(choices=[('Excellent', 'excellent'), ('Average', 'average'), ('Adjustable', 'adjustable')], max_length=20)),
                ('dustbin_availability', models.BooleanField(null=True)),
                ('accommodation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accomodation.accommodation')),
                ('hotel_tier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accomodation.hoteltiers')),
            ],
        ),
    ]
