# Generated by Django 4.2.6 on 2023-11-11 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accomodation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='kettle_availability',
            field=models.BooleanField(null=True),
        ),
    ]
