# Generated by Django 4.2.6 on 2023-11-03 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accomodation', '0002_alter_accommodation_has_tier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='per_day_rent',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
    ]
