# Generated by Django 4.2.6 on 2023-11-03 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accomodation', '0003_alter_room_per_day_rent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='washroom_status',
            field=models.CharField(choices=[('exce', 'Excellent'), ('avg', 'Average'), ('adj', 'Adjustable')], max_length=20),
        ),
    ]
