# Generated by Django 4.2.6 on 2023-11-11 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accomodation', '0003_room_coffee_powder_availability_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='washroom_status',
            field=models.CharField(choices=[('exce', 'Excellent'), ('avg', 'Average'), ('adj', 'Adjustable')], max_length=20, null=True),
        ),
    ]
