# Generated by Django 4.2.6 on 2023-11-03 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accomodation', '0005_room_admission_rate_room_monthly_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='accommodation',
            name='is_pending',
            field=models.BooleanField(default=True),
        ),
    ]
