# Generated by Django 4.2.6 on 2023-11-03 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accomodation', '0006_accommodation_is_pending'),
    ]

    operations = [
        migrations.AddField(
            model_name='accommodation',
            name='image',
            field=models.ImageField(null=True, upload_to='images/accommodation_images/'),
        ),
        migrations.CreateModel(
            name='RoomImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(upload_to='images/room_images/')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accomodation.room')),
            ],
        ),
    ]
