# Generated by Django 4.2.6 on 2023-12-15 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accomodation', '0006_alter_room_per_day_rent'),
    ]

    operations = [
        migrations.AddField(
            model_name='accommodation',
            name='is_rejected',
            field=models.BooleanField(default=False),
        ),
    ]
