# Generated by Django 4.2.9 on 2024-01-31 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accomodation', '0007_accommodation_is_rejected'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accommodation',
            name='monthly_rate',
            field=models.IntegerField(max_length=20, null=True),
        ),
    ]
