# Generated by Django 4.2.9 on 2024-02-03 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accomodation', '0008_alter_accommodation_monthly_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='room_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='accommodation',
            name='monthly_rate',
            field=models.IntegerField(null=True),
        ),
    ]
